'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("reports.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clean the selected file to only the data we will process.
        '''</summary>
        Friend Shared ReadOnly Property AFF_Clean_UP_Clean_File() As String
            Get
                Return ResourceManager.GetString("AFF_Clean_UP_Clean_File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Creates the revised folder and saves the cleaned file in it.
        '''</summary>
        Friend Shared ReadOnly Property AFF_Clean_UP_Save_Cleaned_Json() As String
            Get
                Return ResourceManager.GetString("AFF_Clean_UP_Save_Cleaned_Json", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select the AFF input file you need to clean up.
        '''</summary>
        Friend Shared ReadOnly Property AFF_Clean_UP_Select_File() As String
            Get
                Return ResourceManager.GetString("AFF_Clean_UP_Select_File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End Date Field - Enter just the date, the time will set to 23:59:59.000 automatically..
        '''</summary>
        Friend Shared ReadOnly Property enddate() As String
            Get
                Return ResourceManager.GetString("enddate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Button - Exports the report data to the output file..
        '''</summary>
        Friend Shared ReadOnly Property Export() As String
            Get
                Return ResourceManager.GetString("Export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Type - Type of file for the export file.  Select either CSV or XLSX for the output file format..
        '''</summary>
        Friend Shared ReadOnly Property filetype() As String
            Get
                Return ResourceManager.GetString("filetype", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generate button - Runs the report..
        '''</summary>
        Friend Shared ReadOnly Property Generate() As String
            Get
                Return ResourceManager.GetString("Generate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Output File Button - Open the file dialog box so you can select a newfile and location..
        '''</summary>
        Friend Shared ReadOnly Property output_file() As String
            Get
                Return ResourceManager.GetString("output_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Output Textbox - Output file name and location.  It defaults to your desktop and a excel file named for the report you are running.  .
        '''</summary>
        Friend Shared ReadOnly Property output_TextBox() As String
            Get
                Return ResourceManager.GetString("output_TextBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start Date Field - Enter just the date, the time will set to 00:00:00.00 automatically..
        '''</summary>
        Friend Shared ReadOnly Property startdate() As String
            Get
                Return ResourceManager.GetString("startdate", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
